Create task 3, add class and methods, add tests
AleksandraKasperowicz/invoicing-system-Aleksandra-Kasperowicz pull request #3
Opened 2023-03-04 17:17 UTC by AleksandraKasperowicz

Przesyłam zadanie 3

2023-03-06 19:44 UTC, strzeleckik commented on app/src/main/java/pl/futurecollars/invoicing/App.java
>      System.out.println(new App().getGreeting());
trzymając to w kodzie, za każdym razem jak bedziesz wywoływac testy itp. to bedzie się uruchamiać i dodawać ci do bazy dane, czasami się to może przydać, ale raczej rzadko wiec rekomendowałbym usunąć (jak będziesz chciała coś z tego wykorzystać to cofniesz się w historii commitów), w ostateczności zakomentować

2023-03-06 19:49 UTC, strzeleckik commented on app/src/main/java/pl/futurecollars/invoicing/db/FileDatabase.java
> +    fileService.writeDataToFile("id.txt", currentId + 1);
currentId inkrementujesz 2 razy, może zrób to w jednym miejscu

2023-03-06 19:50 UTC, strzeleckik commented on app/src/main/java/pl/futurecollars/invoicing/db/FileDatabase.java
> +  FileService fileService;
brak modyfikatora dostepu

2023-03-06 19:50 UTC, strzeleckik commented on app/src/main/java/pl/futurecollars/invoicing/db/FileDatabase.java
> +  long currentId;
jak wyżej

2023-03-06 19:51 UTC, strzeleckik commented on app/src/main/java/pl/futurecollars/invoicing/db/FileDatabase.java
> +    fileService.writeDataToFile(idDbPath, currentId + 1);
inkrementujesz dwa razy currentId, może zrób to tylko raz w jednym miejscu ;)

2023-03-06 19:51 UTC, strzeleckik commented on app/src/main/java/pl/futurecollars/invoicing/service/FileService.java
> +    } catch (Exception e) {
tutaj zmieniłem, żeby przy każdym exception zwracało 0

2023-03-06 19:52 UTC, strzeleckik commented on app/src/test/groovy/pl/futurecollars/invoicing/AppTest.groovy
> -
jak nie potrzeba to do usuniecia

2023-03-06 19:53 UTC, strzeleckik commented on app/src/test/groovy/pl/futurecollars/invoicing/db/FileDatabaseTest.groovy
> +        def invoicePath = File.createTempFile("tmpInvoices", 'json')
testy powinny byc przeprowadzone na pliku tymczasowym, innym niż prawdziwa baza danych ;)

2023-03-06 19:54 UTC, strzeleckik requested changes
Dodałem kilka komentarzy, dodatkowo prośba o analizę zmian jakie dodałem w commit ;)

2023-03-06 20:01 UTC, AleksandraKasperowicz commented
super, dziękuje. Będę poprawiać

2023-03-11 08:42 UTC, strzeleckik approved these changes
elegancko ;)

2023-03-11 13:50 UTC, merged