Task 5
AleksandraKasperowicz/invoicing-system-Aleksandra-Kasperowicz pull request #5
Opened 2023-03-11 13:51 UTC by AleksandraKasperowicz

Zadanie 5

2023-03-12 06:37 UTC, AnnLiz22 approved these changes

2023-03-17 06:53 UTC, strzeleckik commented on app/src/main/java/pl/futurecollars/invoicing/db/FileDatabase.java
> +
Brakuje mi tutaj @Repository?

2023-03-17 06:57 UTC, strzeleckik requested changes
public class InvoiceController {

  final InvoiceService invoiceService = new InvoiceService(new FileDatabase(new FileService(), Configuration.DB_PATH, Configuration.ID_DB_PATH));

To jest fragment z twojego InvoiceController, ponieważ od teraz spring zarządza inicjalizacją InvoiceController, InvoiceService i wstrzykiwaniem zależności, to nie powinnaś w InvoiceController inicjalizować sama InvoiceService tylko użyć tego którego zainicjalizował spring ;) Popatrz na demo repozytorium moje czy to z futurecollars jak tam to wygląda, zresztą wygląda to tak samo jak zrobiłaś w innych klasach :)

2023-03-20 20:21 UTC, strzeleckik commented on app/src/main/java/pl/futurecollars/invoicing/configuration/ConfigApp.java
> +  public static final String DB_PATH = "invoice.json";
jak zrobiłaś do tych zmiennych metody getIdPath, getInvoice to nie potrzeba żeby były public mogą być private

2023-03-20 20:22 UTC, strzeleckik commented on app/src/main/java/pl/futurecollars/invoicing/configuration/Config.java
> +public interface Config {
troche przekombinowane, do @Configuration nie potrzeba interfejsu :)

2023-03-20 20:22 UTC, strzeleckik commented on app/src/main/java/pl/futurecollars/invoicing/configuration/Config.java
> +public interface Config {
tak było w skoroszycie?

2023-03-20 20:23 UTC, strzeleckik commented on app/src/main/java/pl/futurecollars/invoicing/configuration/ConfigTest.java
> +public class ConfigTest implements Config {
a do czego to jest używane?

2023-03-20 20:24 UTC, strzeleckik commented on app/src/main/java/pl/futurecollars/invoicing/controller/InvoiceController.java
>  @Generated
to @Generated to do czego?

2023-03-20 20:25 UTC, strzeleckik commented on app/src/main/java/pl/futurecollars/invoicing/db/FileDatabase.java
> +  @Autowired
jak masz @RequiredArgsConstructor to nie potrzebujesz @Autowired przy zmiennych private final... w teorii :)

2023-03-20 20:25 UTC, strzeleckik requested changes
kilka uwag / pytań :)

2023-03-21 09:32 UTC, AleksandraKasperowicz commented
Zmienione.

2023-03-29 15:45 UTC, merged