Task 7
AleksandraKasperowicz/invoicing-system-Aleksandra-Kasperowicz pull request #7
Opened 2023-03-28 12:18 UTC by AleksandraKasperowicz

Zadanie 7

2023-03-28 18:25 UTC, AnnLiz22 approved these changes

2023-03-29 18:17 UTC, strzeleckik commented on app/src/main/java/pl/futurecollars/invoicing/db/memory/InMemoryDatabase.java
> +    log.info("update invoice id = {}", id);
wystarczy samo info (zastosuj wszędzie), debug używaj w miejscach gdzie chcesz "zdebugować" jakiś błąd.

2023-03-29 18:18 UTC, strzeleckik requested changes
drobnostka do zmiany:)

2023-03-29 19:02 UTC, AleksandraKasperowicz commented
Ok, chyba poprawione :)

2023-03-31 19:41 UTC, strzeleckik approved these changes
Pięknie ;)

2023-03-31 19:42 UTC, AleksandraKasperowicz commented
Dziękuje :)

2023-03-31 19:42 UTC, merged