Task 8
AleksandraKasperowicz/invoicing-system-Aleksandra-Kasperowicz pull request #8
Opened 2023-04-01 06:41 UTC by AleksandraKasperowicz

Zadanie 8

2023-04-01 07:39 UTC, strzeleckik commented on app/src/main/java/pl/futurecollars/invoicing/controller/SpringFoxConfig.java
> +public class SpringFoxConfig {
Kosmetyka: przenieś tą klase do package configurations, w package controller powinny być same controllery z API

2023-04-01 07:40 UTC, strzeleckik requested changes
Kosmetyka ;)

2023-04-01 17:16 UTC, AleksandraKasperowicz commented
poprawione

2023-04-02 18:29 UTC, strzeleckik approved these changes
elegancko ;)

2023-04-16 14:24 UTC, merged